language: cpp

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          compiler: gcc
          env: CMAKE_EXTRA_OPTS=""
        - os: linux
          dist: trusty
          sudo: required
          compiler: clang
          env: CMAKE_EXTRA_OPTS="-DCMAKE_CXX_FLAGS=-stdlib=libc++"

addons:
    apt:
        packages:
            - cmake
            - libc++-dev
            - libboost-test-dev
            - libboost-system-dev
            - libboost-filesystem-dev
            - libusb-1.0-0-dev
            - libusb-dev
        sources:
            - ubuntu-toolchain-r-test

before_script:
    - mkdir build
    - cd build
    - cmake $CMAKE_EXTRA_OPTS -DCMAKE_BUILD_TYPE=Debug ..

script:
    - make
    - make check
