#pragma once

#include "entities/Hardware.h"

class IHardwareRequester
{
public:
   //--------------------------------------------------------------
   /// \brief           Add new hardware plugin instance
   /// \param [in] newHardware   New hardware informations
   /// \return          harwareId generated by the database
   //--------------------------------------------------------------
   virtual int addHardware(boost::shared_ptr<CHardware> newHardware) = 0;

   //--------------------------------------------------------------
   /// \brief           Get hardware informations
   /// \param [in] hardwareId   Hardware plugin instance Id
   /// \throw           std::invalid_argument if hardwareId is unknown
   //--------------------------------------------------------------
   virtual boost::shared_ptr<CHardware> getHardware(int hardwareId) = 0;

   //--------------------------------------------------------------
   /// \brief           List all hardware plugin instances
   /// \return          List of registered plugin instances
   //--------------------------------------------------------------
   virtual std::vector<boost::shared_ptr<CHardware> > getHardwares() = 0;

   //--------------------------------------------------------------
   /// \brief           Update hardware informations
   /// \param [in] hardwareId   Hardware plugin instance Id
   /// \param [in] newConfiguration   New configuration
   //--------------------------------------------------------------
   virtual void updateHardwareConfiguration(int hardwareId, const std::string& newConfiguration) = 0;

   //--------------------------------------------------------------
   /// \brief           Remove hardware plugin instance
   /// \param [in] hardwareId   Hardware plugin instance Id
   //--------------------------------------------------------------
   virtual void removeHardware(int hardwareId) = 0;

   //--------------------------------------------------------------
   /// \brief           Enable/disable hardware plugin instance
   /// \param [in] hardwareId   Hardware plugin instance Id
   /// \param [in] enable       true to flag as enable, false to flag as disable
   //--------------------------------------------------------------
   virtual void enableInstance(int hardwareId, bool enable) = 0;

public:
   virtual ~IHardwareRequester()
   {
   }
};
