#pragma once

#include "entities/Entities.h"


namespace database { 

   class IMessageRequester
   {
   public:
      //--------------------------------------------------------------
      /// \brief           Add new Message 
      /// \param [in]      newMessage   New XplMessage informations
      /// \param [in]      messageContent  The XplMessage content
      /// \return          message Id generated by the database
      /// \throw           shared::exception::CEmptyResult if fails
      //--------------------------------------------------------------
      virtual int insertMessage(const entities::CMessage & newMessage, const std::vector<entities::CMessageContent> & messageContent) = 0;

      //--------------------------------------------------------------
      /// \brief       Destructor
      //--------------------------------------------------------------
      virtual ~IMessageRequester()
      {
      }
   };
 
} //namespace database 
