#pragma once

#include "entities/Entities.h"


namespace database { 

   class IXplMessageRequester
   {
   public:
      //--------------------------------------------------------------
      /// \brief           Add new XplMessage 
      /// \param [in]      newXplMessage   New XplMessage informations
      /// \param [in]      messageContent  The XplMessage content
      /// \return          xplMessage Id generated by the database
      /// \throw           shared::exception::CEmptyResult if fails
      //--------------------------------------------------------------
      virtual int addXplMessage(const entities::CXplMessage & newXplMessage, const std::vector<entities::CXplMessageContent> & messageContent) = 0;

      //--------------------------------------------------------------
      /// \brief       Destructor
      //--------------------------------------------------------------
      virtual ~IXplMessageRequester()
      {
      }
   };
 
} //namespace database 
